USE smarthomedb;

CREATE TABLE DEVICES (
    ID          INT NOT NULL AUTO_INCREMENT,
    TYPE        ENUM("LIGHT", "SWITCH", "THERMOSTAT", "DIMMING_LIGHT", "COLORED_LIGHT"),
    NAME        VARCHAR(255),
    INIT        VARCHAR(8000),
    VARS        VARCHAR(8000),
    PRIMARY KEY (ID)
);

CREATE TABLE LIGHTS (
    ID              INT NOT NULL,
    TYPE            ENUM("LIGHT") NOT NULL,
    ON_CMD          VARCHAR(8000),
    OFF_CMD         VARCHAR(8000),
    GET_STATE_CMD   VARCHAR(8000),
    PRIMARY KEY (ID),
    FOREIGN KEY (ID) REFERENCES DEVICES (ID) ON DELETE CASCADE
);

CREATE TABLE DIMMING_LIGHTS (
    ID              INT NOT NULL,
    TYPE            ENUM("DIMMING_LIGHT") NOT NULL,
    ON_CMD          VARCHAR(8000),
    OFF_CMD         VARCHAR(8000),
    GET_STATE_CMD   VARCHAR(8000),
    SET_BRIGHTNESS  VARCHAR(8000),
    PRIMARY KEY (ID),
    FOREIGN KEY (ID) REFERENCES DEVICES (ID) ON DELETE CASCADE
);

CREATE TABLE COLORED_LIGHTS (
    ID              INT NOT NULL,
    TYPE            ENUM("COLORED_LIGHT") NOT NULL,
    ON_CMD          VARCHAR(8000),
    OFF_CMD         VARCHAR(8000),
    GET_STATE_CMD   VARCHAR(8000),
    SET_BRIGHTNESS  VARCHAR(8000),
    SET_RGB         VARCHAR(8000),
    PRIMARY KEY (ID),
    FOREIGN KEY (ID) REFERENCES DEVICES (ID) ON DELETE CASCADE
);


CREATE TABLE SWITCHES (
    ID              INT NOT NULL,
    TYPE            ENUM("SWITCH") NOT NULL,
    ON_CMD          VARCHAR(8000),
    OFF_CMD         VARCHAR(8000),
    GET_STATE_CMD   VARCHAR(8000),
    PRIMARY KEY (ID),
    FOREIGN KEY (ID) REFERENCES DEVICES (ID) ON DELETE CASCADE
);


CREATE TABLE THERMOSTATS (
    ID          INT NOT NULL,
    TYPE        ENUM("THERMOSTAT") NOT NULL,
    GET_TEMP    	VARCHAR(8000),
    SET_TEMP        VARCHAR(8000),
    FAN_ON_CMD      VARCHAR(8000),
    FAN_OFF_CMD     VARCHAR(8000),
    COOL                VARCHAR(8000),
    HEAT                VARCHAR(8000),
    AUTO                VARCHAR(8000),
    PRIMARY KEY (ID),
    FOREIGN KEY (ID) REFERENCES DEVICES (ID) ON DELETE CASCADE
);


CREATE TABLE USERS(
  ID  INT NOT NULL AUTO_INCREMENT,
  USERNAME VARCHAR(8000) NOT NULL,
  PASSWORD VARCHAR(8000) NOT NULL,
  SESSION_KEY VARCHAR(8000),
  PRIMARY KEY (ID)
);

COMMIT;
